version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "monday:09:00"
      base: "develop"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
